CREATE TABLE IF NOT EXISTS Books (
BookID INTEGER PRIMARY KEY AUTOINCREMENT,
Title TEXT NOT NULL,
Author TEXT NOT NULL,
Quantity INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS Members (
MemberID INTEGER PRIMARY KEY AUTOINCREMENT,
FirstName TEXT NOT NULL,
LastName TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS Loans (
LoanID INTEGER PRIMARY KEY AUTOINCREMENT,
BookID INTEGER NOT NULL,
MemberID INTEGER NOT NULL,
BorrowDate TEXT NOT NULL,
ReturnDate TEXT,
FOREIGN KEY (BookID) REFERENCES Books(BookID),
FOREIGN KEY (MemberID) REFERENCES Members(MemberID)
);